### ISSUE TITLE
Run ptw with -s

### ISSUE THREAD

**Issue by av-guy** [joeyespo/pytest-watch#113]
Hey,

I'm sorry if this has been asked before, or I am just missing it in the documentation, but how would I go about running ptw and capturing stdout/stderr?

Thanks in advance!

**Comment by av-guy** [comment]
I fixed this by passing capsys to my test function. Sorry for the confusion. Closing this issue now.

**Comment by Olshansk** [comment]
So is there a recommended way to run the equivalent of `pytest -s` using `ptw` without needing to modify the actual src code?

I've looked through `ptw --help`, and the verbosity flag was the closest one I could find but does have the intended result.

**Comment by glockenbach** [comment]
@Olshansk I wanted to do the same.

`Usage: ptw [options] [--ignore <dir>...] [<directory>...] [-- <pytest-args>...]`

hence, try: `ptv -- -s`
