### ISSUE TITLE
Integration with pytest-cov

### ISSUE THREAD

**Issue by C0DK** [joeyespo/pytest-watch#116]
Currently i cannot, in anyway i can see, generate a coverage report while using your tools. This saddens me as i have to run that additionally once in a while.

**Comment by marcinowski** [comment]
Correct me if I'm wrong but I think you're able to run any additional pytest command with `ptw -- ` like for example `ptw -- --cov` for coverage.
```
$ ptw --help
Usage: ptw [options] [--ignore <dir>...] [<directory>...] [-- <pytest-args>...]
```

**Comment by C0DK** [comment]
Yes sorry, I was stupid haha.
