### ISSUE TITLE
`ImportError` when running tests using `ptw`

### ISSUE THREAD

**Issue by sohang3112** [joeyespo/pytest-watch#129]
I have a folder structure like this:

```
root
|- title_api.py
|- tests
    |- test_title_api.py
```

Content of `test_title_api.py` is:
```python
from title_api import *

def test_dummy():
    assert False
```

Running `pytest` in the `root` directory successfully runs `test_dummy`. But when `ptw` is run in the `root` directory, it complains of an `ImportError` as Python can't find `title_api` module.

`pytest-watch` should work similarly to `pytest` here (add the parent directory to `sys.path` before running tests).

**Notes:** 
- I install latest commit of `pytest-watch` from its Github url.
- I am running version `7.2.0` of `pytest` in Python 3.11. 
- My OS is Windows 11.

**Comment by kirkbroadhurst** [comment]
I have experienced this issue myself.

It seems to be resolved by adding an `__init__.py` file to your `tests` folder.

I haven't dug in to explore why it occurs. Adding an (empty) `__init__.py` to your `tests` folder can have other impacts, mostly around static analysis, but is generally pretty safe / minor.

**Comment by sohang3112** [comment]
> It seems to be resolved by adding an __init__.py file to your tests folder.

Thanks, this worked.
