### ISSUE TITLE
Improve `--ignore`

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/pytest-watch#13]
Let's continue [the discussion](https://github.com/aldanor/pytest-watch/commit/b4135b7bacb062e4d44d038c6a9cf7a5d93b3c07#commitcomment-11399716) on how to improve the [current](https://github.com/aldanor/pytest-watch/commit/2181ce29f2eeff4fc3b4aa59f512c5086c325814) single-level `--ignore` (alternatively, `--norecursedirs`). #6 was the original issue.

#### Summary

The core problem is that we need a way to exclude directory trees from the watch list. If we don't, `ptw` can crawl to a halt walking the entire tree or worse, use up the system's file resources.

Not all operating systems handle recursive watching natively, so using solutions like [inotify](http://linux.die.net/man/1/inotifywait) (Linux) and [kqueues](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/kqueue.2.html) (Mac) adds a new watch to each subdirectory instead of just one at the root. (Note that some systems do, like the Windows API and Mac's [FSEvents](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/).)

So we need to balance simplicity and efficiency. As mentioned above, not all platforms need a custom recursive solution, so using one in those cases hurts instead of helps.

Another idea is to shop around. If watchdog or another 3rd-party library exposes an efficient cross-platform solution (recursive watching/ignoring on Linux, and `PatternMatchingEventHandler` or a regex solution like #7 for Windows and Mac), we could pass it along instead of re-implementing it.

**Comment by joeyespo** [comment]
@aldanor, any more thoughts on this?

**Comment by aldanor** [comment]
My point was this (it's easier to illustrate it with an example):
```
/foo
/bar
/foo/bar
/foo/foo
/foo/foo/hello
/foo/foo/world
```
Let's say with want to ignore `bar`. Because watchdog doesn't allow us to plug into observer's recursion logic unless we reimplement it, we have to walk the entire directory tree oursevels (just ONCE though) and figure out the folder we want to watch: if all of the subfolders in a folder are watched, then watch this folder; if at least one of the subfolders is ignored, watch all of the non-ignored subfolder, e.g. in the example above it would be
```
/foo
/foo/foo
```
This could be easily implemented and it would work fine imo, chances are you're not going to have 15-level deep source tree with hundred thousand files you need to watch in it.

**Comment by joeyespo** [comment]
@aldanor Yeah, that makes sense.

My point was just that this is a Linux-only thing, since Windows and Mac both have methods to watch `/foo` at the operating system level, allowing us to handle ignored paths in the callback efficiently. (This works because watchdog can put a single watcher at the root instead of walking the full directory tree.) So because of that, let's try to keep things as simple, or see if there's another solution altogether since this would introduce a good bit of complexity to the project.

**Comment by aldanor** [comment]
> allow us to efficiently filter ignored paths in the callback
This just doesn't work at all on Linux -- as I said, if you have a virtualenv (or `.tox`, quite commonly) folder in the source tree, the handler is never triggered at all -- it just gets completely swamped by thousands of files and folders (and that's on a production grade 48-core server with a raid array, lol).

The choice here is between something that works on all platforms but could work more optimally on some and something that just plain doesn't work on some platforms. Plus, I don't think there's such a huge overhead on watching e.g. 10 folders? For a typical source tree, my method (even a full-depth implementation and not a top-level one) would only make you watch several folders. Give me a single example of a repo where that wouldn't be true and there would be a noticeable overhead of launching multiple observers?

The worst case scenario for my method is when you have a source tree 15 levels deep and a single folder all the way down at the 15-th level that you have to ignore. Then you sort of have to subscribe to all folders on all 14 levels. But is that at all likely? 

The best case scenario is when you have to ignore a few folders at the root level, and that's most often the case.

**Comment by aldanor** [comment]
Now that I think about, this could be related to me having to use polling observer on Linux; maybe we could ignore events at the handler level for non-polling observers and at the observer level for polling (because then it has to keep track of snapshots which makes it blow up)?

This will need to be confirmed though.

**Comment by joeyespo** [comment]
> The choice here is between something that works on all platforms but could work more optimally on some and something that just plain doesn't work on some platforms

Well, we could special-case the Linux implementation so it's optimized for all three major platforms. My point was that we should look for the right abstraction so we don't have to hand-code the special case. Whether that be watchdog or another library. "Should I take advantage of the OS, or manually wire-up watches to all subdirectories" ideally shouldn't be `ptw`'s concern.

> Plus, I don't think there's such a huge overhead on watching

Just like you don't want to optimized this project for Mac / Windows, I don't really want to give up the OS-level optimizations of non-Linux. (I don't want to *exclude* Linux either.) So let's keep those optimizations in place and do the custom thing when using observers that don't take advantage of the underlying OS (namely, `inotify`, `kqueues`, and `polling`). I'm suggesting that we find a way to defer this to a lower abstraction library like watchdog or a watchdog plugin. This allows *all* projects that monitor a directory tree to take advantage of this optimization, not just `ptw`.

**Comment by joeyespo** [comment]
> Now that I think about, this could be related to me having to use polling observer on Linux

Why are you using a polling observer? (Are you using `--poll`?)

**Comment by aldanor** [comment]
I had to use `--poll` on the Linux box at work because it just wouldn't work without it for some reason.

**Comment by joeyespo** [comment]
That's odd. Want to get to the bottom of that then?

Are you working in a virtual machine? That's the primary use case for `--poll` right now.

**Comment by aldanor** [comment]
Nope, it's remote server with an NFS mount. I'm actually editing files from Windows and it picks it up from Linux remotely.

**Comment by joeyespo** [comment]
@aldanor Is this still an issue for you? v4.0 was just published, which forwards `--ignore` to pytest and has improved internals that might help.

I'm closing as an effort to clean up issues, but feel free to re-open or open a new issue with some more specifics from 4.0 onward.
