### ISSUE TITLE
File changes are not being picked up by pytest

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/pytest-watch#15]
Ever since switching to use `py.test`, the test files are being cached. Possibly because pytest is using `import` to load and run the tests with? Here's [the related Pytest issue](https://github.com/pytest-dev/pytest/issues/793).

If it can be fixed there, we can continue on. If not, we'll have to go back to using [the `shell=True` approach](https://github.com/aldanor/pytest-watch/commit/dc066e212dbbbf03af74162f9d449c5866a87e2b) or see what else we can do to be sure arguments are quoted properly in a cross-platform way.

**Comment by joeyespo** [comment]
Fixed this in `v3.1`. Keeping this issue open until we know whether `pytest` can and will address this.

**Comment by blueyed** [comment]
As per https://github.com/pytest-dev/pytest/issues/793 this is unlikely to get fixed in `pytest´.

**Comment by joeyespo** [comment]
Yeah, looks like this isn't getting fixed by py.test.

Closing this since it was fixed on all platforms as of #18.
