### ISSUE TITLE
Hook to be run before running pytest / configure py.test command

### ISSUE THREAD

**Issue by blueyed** [joeyespo/pytest-watch#24]
Instead of only calling `py.test`, it would be nice to be able to configure some hook to be run before it.

The workaround appears to be creaating a `py.test` wrapper script that would do this, and prepend it via $PATH.  But it would be more comfortable to configure the path to `py.test` itself, which could be this wrapper script then.

**Comment by joeyespo** [comment]
Agreed. Would using a CLI argument like with `--onpass` / `--onfail` work?

Say, `--onstart`, `--pretest`, or `--beforerun`?

**Comment by blueyed** [comment]
Yes.

`--beforerun` seems good.
