### ISSUE TITLE
Add some documentation for extra parameters

### ISSUE THREAD

**Issue by bendtherules** [joeyespo/pytest-watch#29]
Optional parameters like "-ignore" or others don't seem to be documented right now. Atleast, I was not able to find it. So, it will be better to put it in the readme.

**Comment by bendtherules** [comment]
Same as #35. So, closing for now.

**Comment by bendtherules** [comment]
Close #29.

Same as #35. So, closing for now.

**Comment by joeyespo** [comment]
Whoops, didn't check the issues before posting that. Thanks for opening and then closing just now.
