### ISSUE TITLE
Add --onstart similar to --onexit

### ISSUE THREAD

**Issue by bendtherules** [joeyespo/pytest-watch#32]
ptw currently has `--onexit`, but no `--onstart` - There should be no reason for this asymmetrical design. There is already `--beforerun`, but it is run before every run of pytest and so, isn't a good candidate for initialising something just once.

It can be useful for starting things like a external notifier, which wants to run for the whole duration of ptw.

Adding it should be trivial.

**Comment by joeyespo** [comment]
Unlike the `--onexit` option, there isn't a strong case for its dual aside from the purity of symmetry. `--onstart` can be accomplished outside of ptw pretty easily, e.g. `myscript && ptw`. However, `--onexit` solves a practical problem where you need to run some explicit cleanup code before terminating from an external script environment, e.g. a Makefile or `npm run`. (In retrospect, `--finally` may be a better name than `--onexit` to match the common try-finally concept. This name might better indicate that there isn't some "missing" dual feature.)

Symmetry is a nice property to have in theory and mathematics, but it can easily lead to clutter and over-engineering when it comes to software design. Adding a feature is usually much easier than maintaining it, so triviality isn't exactly a good indicator of necessity.

Thanks for the suggestion.
