### ISSUE TITLE
Evaluate good module for creating test directory structures

### ISSUE THREAD

**Issue by bendtherules** [joeyespo/pytest-watch#34]
I'd really like to add some tests for the ini_config code first.

For that, we need a easy way of creating directory structures with some content filled in some files, somewhat like [what can be done in cloud-init config files](https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting#write-files-to-the-disk). Cloud-init seems too heavy and unix-specific. There is also Cloudbase-init for Windows.

We could write separate helpers for this, but it is better to shop for good modules instead. This are the ones I could find easily : [testdata](https://github.com/Jaymon/testdata) and [pyboiler](https://github.com/Link-/pyboiler). Also, this blog post (http://btmiller.com/2015/03/17/represent-file-structure-as-yaml-with-python.html) can be a starting point

None of them can set the file contents though.

We need to choose one, that will also be used in other tests.

**Comment by joeyespo** [comment]
:+1: for tests. Pretty amusing that a testing tool has no tests, huh?

I don't think we need anything heavy though. We don't necessarily need randomized data to test the wire-up the ptw provides. All we really need is a `tests/` directory with a few `test_xx.py` files and subdirectories that mimic real projects (e.g. some that include a `pytest.ini` to ensure that the config wire-up is working).

**Comment by bendtherules** [comment]
To clear myself, I didn't mean filling those files with randomised data, but more like filling necessary files like pytest.ini in a declarative manner, as possible in cloud-init.
Something like this

    -test_asd.py
    -asd.py
    -pytest.ini
        content:
        [pytest-watch]
        verbose = True

**Comment by joeyespo** [comment]
What advantage does that have over having a literal such as `tests/example-project/pytest.ini` that contains the same thing:

```ini
[pytest-watch]
verbose = True
```

**Comment by joeyespo** [comment]
Closing this because I don't plan to have any generated directories as of right now. I think having a directory of test projects is more stable, visible, and as declarative as putting the same information into a config file.

On the other hand, the downside to having literal files instead of generated ones is that you can't combine them. I don't think it's a big advantage in this particular project since we can cover most ptw cases with just a few test projects. But if that becomes unwieldy, I'm definitely willing to use tools to help. Doing that from the get-go is just too much of a pre-optimization.

Thanks for the suggestion, @bendtherules.

**Comment by bendtherules** [comment]
You are right that it doesnt make much of a difference. I was just thinking that it will help generate the structure in a temporary directory to make sure improper tests dont dirty the actual directories, but maybe we can just copy it over to get the same effect.

**Comment by joeyespo** [comment]
@bendtherules Oh yes, that's a good point. The technique I've been using is to use temp directories for that purpose, copying files over like you're suggesting. Not all tests will require file changes though, so some tests can function without the extra overhead. Luckily, git will let us see if we accidently set up tests that write to those "read-only" directories.
