### ISSUE TITLE
Wait for the previous pytest process to exit before re-running

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/pytest-watch#36]
The proposal is to send `SIGTERM` to the pytest process when pytest-watch observes a file change. It'll then wait for the process to finish before starting the new cycle.

This will solve #23 as well as any other quirky behavior that comes from having two pytest instances running the same test suite.

This could also help with #21. The underlying question is what to do when a test initiates an interactive session like `pdb`. If `pdb` ignores our termination signal, we're done. If not, we may also need a `--full` CLI argument to tell pytest-watch to wait out the full test session before starting the new one. Similar to how pytest [automatically adds](https://pytest.org/latest/usage.html#setting-a-breakpoint-aka-set-trace) `-s` when you use `--pdb`, pytest-watch can automatically add `--full` when `--pdb` is present in pytest's argument list or in the config file.

**Comment by syradium** [comment]
Well I think this can be easily solved just by adding a non-blocking lock to the `ChangeHandler.run(...)`  for example . At least I did so. 

When we drop into pdb your watcher freezes here https://github.com/joeyespo/pytest-watch/blob/master/pytest_watch/watcher.py#L111. So we can just prevent us from reaching this point when there is another `subprocess` waiting.

Yes, this can be controlled by the `--full` arg. But the name seems a little bit confusing.

**Comment by joeyespo** [comment]
Fixed with 0cf6b93966320847600c9b50699f00adeb63d307.

Just published v4.0, which includes this.
