### ISSUE TITLE
Show which file has changed instead of just 'Changes detected'

### ISSUE THREAD

**Issue by joeyespo** [joeyespo/pytest-watch#39]

**Comment by bendtherules** [comment]
That is just what the `--verbose` option does.

**Comment by joeyespo** [comment]
@bendtherules Yeah, other tools do this by default and I've found it to be helpful. Namely, most web servers I've used when running in debug mode.

**Comment by joeyespo** [comment]
Fixed with 4c0524765dafb5bac07bf0fa6faa2eec6caeb0be.

Just published v4.0, which includes this.
