### ISSUE TITLE
ini path collected doesnt respect pytest options -c and [file_or_dir]

### ISSUE THREAD

**Issue by bendtherules** [joeyespo/pytest-watch#40]
From pytest docs:
> usage: `py.test [options] [file_or_dir] [file_or_dir] [...]`
>
> positional arguments:
>   file_or_dir
>
> general:
>   `-c file` - load configuration from `file` instead of trying to locate one of the implicit configuration files.

Both the `file_or_dir` and `-c` options, when supplied can effectively change the directory tests get loaded from.
`ptw` should also try to locate `pytest.ini` file from there, which it doesnt as the args list is not passed while locating ini path. Maybe we should do that?

Soln 1: Pass whole arg list, alongwith `--collect-only`
-----------------------------------------------------------------

One problem is that some plugins (like pytest-cov ) are a bit odd (or, maybe they have some reason) and don't respect the `--collect-only` flag. So, if we do add all args, it might not be as much a dry-run as we would like it to be and have side-effects (like, pytest-cov generates coverage of tests collected ). 
On other hand, it might not be too much of side-effect, as we are going to run the tests anyway in the next step. But we should still mention this in docs, lest someone wants to disable this.

Soln 2: Parse its arg list and only pass in this two options
-------------------------------------------------------------------------

Most desirable result. But parsing and trying to guess the important parameters makes `ptw` less robust and prone to `pytest` changes, not to mention the code repetition from pytest

**Comment by joeyespo** [comment]
Oh, interesting. You're right, this isn't what you'd expect.

I like your 1st solution. It's an easy change and will ensure the collection step works identically to the actual pytest call. If a plugin doesn't respect that flag, it should probably be reported as an issue.

Up for tackling this?

**Comment by bendtherules** [comment]
Yes, I'll give a try.

**Comment by joeyespo** [comment]
Fixed with ede80ffa64f52570658aa82dd20162e2c9a6439c and 2637366a73ad7e1feec2d337bef8f91431fac5b7.

Just published v4.0, which includes these. Feel free to open another issue if there's still problems with config collection! Thanks for the issue, @bendtherules!
