### ISSUE TITLE
Allow setting <directories> argument from pytest.ini

### ISSUE THREAD

**Issue by bendtherules** [joeyespo/pytest-watch#41]
Repost from my code [comment](https://github.com/joeyespo/pytest-watch/commit/7c75e25664e41921a5055bc71b23a28981206882#commitcomment-14795948)

`<directories>` option which can be in cmdline cant be set from pytest.ini as the cmdline arguments which don't start with `--` dont get overloaded from ini.

There should be a way to do that.

**Comment by joeyespo** [comment]
Closing for the reasons explained in the comment's response.
