### ISSUE TITLE
Might exit silently with exit code 2 (in merge_config)

### ISSUE THREAD

**Issue by blueyed** [joeyespo/pytest-watch#43]
`merge_config` might make `ptw` exit silently with code 2, when there are missing pytest plugins:

Removing `with silence()` shows this:

> usage: ptw [options] [file_or_dir] [file_or_dir] [...]
ptw: error: unrecognized arguments: --reuse-db --dc=Tester
  inifile: …/project/setup.cfg
  rootdir: …/project/project

Source: https://github.com/joeyespo/pytest-watch/blob/3037f55932634026d7eaedfd958952ad6bf2bc1d/pytest_watch/config.py#L28-L29

It would be good to display the errors from `py.test` in this case.

This issue was triggered when I've tried to use `pytest-watch` installed globally using https://github.com/mitsuhiko/pipsi/.

**Comment by blueyed** [comment]
This also happens (with exit code 1) in case of something like an `ImportError` (via `pytest_load_initial_conftests` => `_setup_django` from pytest-django).

I've also noticed that `merge_config` does not use the `directories` passed to `ptw` (which gets cleaned up / split according to `--` only after `merge_config` however).

**Comment by blueyed** [comment]
See #45.

**Comment by joeyespo** [comment]
@blueyed Wow, didn't know you could reference a comment in a commit message. How'd you do that?

**Comment by joeyespo** [comment]
Thanks for the issue and its fix :+1:

**Comment by blueyed** [comment]
@joeyespo 
> Wow, didn't know you could reference a comment in a commit message. How'd you do that?

Just copy the link?! (from the permalink / "commented X ago").

**Comment by joeyespo** [comment]
@blueyed Makes sense. Very cool.
