### ISSUE TITLE
multiple directories support

### ISSUE THREAD

**Issue by rakjin** [joeyespo/pytest-watch#5]
It would be great if:

    ptw [options] [<directory> ...]

rather than:

    ptw [options] [<directory>]

I managed to [patch](https://github.com/rakjin/pytest-watch/commit/0aa5b27afa291ebd3c58b6b15ce814153e1c3a2f) this for my personal use.
But I hope this could be done in simpler way with `plugin`.
How about changing your main logic
 - from wrapping around and system-calling `py.test ...`
 - to being a `pytest-plugin` and adding `entry_points={ 'pytest11': ... }` to your `setup.py`? (like other `pytest-something` plugins do)

Anyway, this is my wish:

    py.test --watch --onfail='...' --onpass='...' tests

for watching and testing `tests/`, or

    py.test --watch-dir=mypackage --onfail='...' --onpass='...' tests examples

for watching `mypackage/` but testing `tests/` and `examples/`.
Or some better interface could be possible...

Thanks for reading this and releasing v2!

**Comment by joeyespo** [comment]
This is how `pytest` works, right?

I was actually thinking something similar. Except instead of taking specific arguments, have `pytest-watch` take *any* argument and just pass the unsupported ones along to `pytest`. That'll keep things simple and make sure that all `pytest` options are supported.

Does that make sense?

**Comment by joeyespo** [comment]
Although hmm, `pytest-watch` still needs to know where to watch. Let me think more about this.

**Comment by rakjin** [comment]
Don't mind the dumb `--pytest-options` in my patch. This is a temporal code just for me.
Becoming a plugin will solve the option-passing problem, IMHO.

**Comment by joeyespo** [comment]
Gotcha. Yeah, agreed.

Thinking about it more, I think your solution is pretty elegant. Would you be interested in pulling latest and applying your changes to that? I made a comment in your commit. Other than that, I'll pull it in if you do make a PR against the latest.

The only things left would be to forward the `pytest` options (for those who want to continue using the `ptw` program), and to create a proper Pytest plugin (I do agree this would be useful).

**Comment by rakjin** [comment]
ok I'll try.

**Comment by aldanor** [comment]
@rakjin Fixed in #11!

**Comment by joeyespo** [comment]
Released pytest-watch 3.0.0 today, which includes the fix from #11.

Be sure to `pip install --upgrade pytest-watch`!

**Comment by aldanor** [comment]
:+1:
