### ISSUE TITLE
-v to increase verbosity

### ISSUE THREAD

**Issue by juanpabloaj** [joeyespo/pytest-watch#69]
I try to use -v to increase verbosity of the output of the pytest to get a full diff

     Use -v to get the full diff 

with pytest -v work fine, I get the full diff. But when I use `-v` with `ptw` I don't get the full diff

**Comment by blueyed** [comment]
How do you call it?

`ptw <dir> -- -v`?

**Comment by blueyed** [comment]
(without `--` you make `ptw` verbose, not pytest)

**Comment by juanpabloaj** [comment]
thanks @blueyed , `--` solve my problem
