### ISSUE TITLE
python -m ptw doesn't work

### ISSUE THREAD

**Issue by max-sixty** [joeyespo/pytest-watch#97]
Thanks again for the awesome library.

The standard method to run modules in different versions of python is `python[23] -m foo`. But that doesn't seem to work with `ptw`:

```
python2 -m ptw 
# /usr/local/opt/python@2/bin/python2.7: No module named ptw
```

**Comment by patallen** [comment]
I know this is a pretty old issue, but the reason this isn't working for you is because the module isn't named 'ptw'.

This works:

```
python2 -m pytest_watch
```

**Comment by max-sixty** [comment]
Ah great, good point!
